config/routes.rb
Learnbystory::Application.routes.draw do
  post "/users/save_word/:id" => "users#save_word"
  post "/users/review_word/:id" => "users#review_word"
  match "/read" => 'stories#show', :as =>"read"
  resources :words

  resources :stories

  resources :sessions, :except => [:edit, :update, :index]

  resources :users do
    collection do
      get "admin"
      post "admin_create"
    end
  end

  root :to => 'stories#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :password, :password_confirmation
  has_and_belongs_to_many :words

  validates :email, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_authentication, :only => [:new, :create, :edit]
  before_filter :require_admin_authentication, :only => [:index]    # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new
    @action = "create"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @action = "update"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to stories_path, notice: '                                  Welcome! you are now logged in.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id][:word_id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def save_word
      if @current_user.words << Word.find(params[:id])
        respond_to do |format|
          format.js { render :action => "save_word" }
        end
      end
  end


   def review_word
     sleep 1
     @words = @current_user.words
     @incomplete_tasks = Word.where(:is_complete => false)
     @complete_tasks = Word.where(:is_complete => true)

     respond_to do |format|
       format.html
       format.json { render json: @user }
     end
   end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
# instanciating user (all attributes)
  def admin
    @user = User.new
    @action = "admin_create"
  end

  def admin_create
    @user = User.new(params[:user])
    @user.is_admin=true
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- this is why @user is created in new -->
<%= form_for(@user, :url => { :action => x }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

<!--   <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.password_field :is_admin %>
  </div> -->
  <%= f.submit 'submit', :class => "small button" %>
  <div class="actions">
  </div>
<% end %>

app/views/users/admin.html.erb
<h1>Sign up as Admin!</h1>

<%= render :partial=>"form", :locals =>{:x=>@action} %>

<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<div class="row">
  <div class="large-4 columns"></div><h1>Edit your account</h1></div>
  <div class="large-8 columns"></div>


  <div class="row">
    <div class="large-4 columns">


<%= render :partial=>"form", :locals =>{:x=>@action} %>

</div>

  <div class="large-8 columns">

  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'New User', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <!-- <th>Password digest</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
   <!--  <td><%= user.password_digest %></td> -->
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<div class="row">
  <div class="large-4 columns"></div><h1>Sign up!</h1></div>
  <div class="large-8 columns"></div>
</div>


<div class="row">
  <div class="large-4 columns">



<%= render :partial=>"form", :locals =>{:x=>@action} %>

</div>

  <div class="large-8 columns">

  </div>
</div>

app/views/users/review_word.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
   <div class="incomplete_words">
      <h1> Review List </h1>
        <table>
          <tr>
            <td>Word</td>
            <td>Definition</td>
            <td>Sentence</td>
            <td>Story</td>
            <td>Done</td>
          </tr>
          <% @current_user.words.each do |x| %>
              <% if x.is_complete == false %>
                  <tr id="edit_word_<%= x.id %>">
                    <td><%= x.name.capitalize %></td>
                    <td><%= x.definition %></td>
                    <td><%= simple_format(x.sentence) %></td>
                    <td><%= x.story.name%></td>
                    <td><%= render :partial => "words/complete", :locals => {:word => x} %></td>
                  </tr>
              <% end %>
          <% end %>
     </table>
  </div>

     <div class="words">
       <h2>Finished Words</h2>
         <% if @complete_words != nil %>
          <table id="complete_words">
            <tr>
              <td>Word</td>
              <td>Definition</td>
              <td>Sentence</td>
              <td>Story</td>
            </tr>
            <% @complete_words.each do |complete_word| %>
            <tr>
              <td><%= complete_word.name.capitalize %></td>
              <td><%= complete_word.definition %></td>
              <td><%= simple_format(complete_word.sentence) %></td>
              <td><%= complete_word.story.name%></td>
              <td><%= render :partial => "words/complete", :locals => {:word => complete_word} %></td>
            </tr>
            <% end %>
          </table>
         <% else %>
            <p>You haven't learned any words yet...</p>
         <% end %>
      </div>
</div>

<%= link_to 'Back', words_path %>

app/views/users/save_word.js.erb
alert("saved for review");

app/views/users/show.html.erb
<h1>Account info</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<!-- <p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p> -->

<%= link_to 'Edit', edit_user_path(@user) %>