config/routes.rb
Learnbystory::Application.routes.draw do
  post "/users/save_word/:id" => "users#save_word"
  post "/users/review_word/:id" => "users#review_word"
  match "/read" => 'stories#show', :as =>"read"
  resources :words

  resources :stories

  resources :sessions, :except => [:edit, :update, :index]

  resources :users do
    collection do
      get "admin"
      post "admin_create"
    end
  end

  root :to => 'stories#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :name, :content, :words
  has_many :words
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  skip_before_filter :require_authentication, :only => [:index]


  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    @words = Word.all

    @user = User.create(params[:word_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %> <br />

    <%= f.label :content %> <br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

app/views/stories/index.html.erb
<div class="row">

</div>
  <div class="large-4 columns"></div>

<div class="row">

  <div class="large-8 columns">
    <% if @current_user.nil?%>
    <p>intro to this page intro to this page intro to this page intro to this page intro to this page intro to this page intro to this page intro to this page</p>
      <img src="http://i3.squidoocdn.com/resize/squidoo_images/590/draft_lens12043801module109670801photo_1278876605how_to_draw_books.jpg">
      <% else %>
   <!--  <h1>Choose your story</h1> -->
   <h1>Stories</h1>

      <% unless  !@current_user.nil? && @current_user.is_admin==true%>
      <p>Decide whether you want to read a story or review words.</p>
      <%end %>
<table>
  <!-- <thead>
    <tr>
      <th></th>

    </tr>
  </thead> -->

  <tbody>
    <td><% if !@current_user.nil? && @current_user.is_admin==true%>
    <%= link_to 'New Story', new_story_path %>
    <% end %> </td>
  <% @stories.each do |story| %>
    <tr>

      <td><h2 class="subheader"><%= story.name %><h2></td>
      <td><%= link_to 'Read', story %></td>
      <% if !@current_user.nil? && @current_user.is_admin==true%>
      <td><%= link_to 'Edit', edit_story_path(story) %></td>
      <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <% end %>
    </tr>
  </tbody>
</table>


<br />

<div class="large-8 columns">

<%end%>

</div>
</div>

app/views/stories/landing.html.erb
WELCOME

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
    <div style="width:900px;">
      <div class="storyblock" style="float:left;width:500px">


        <p>
          <h3 class="subheader"><strong><%= @story.name %></strong></h3>
          <%= simple_format(@story.content) %>
        </p>

    <br/>
    <br/>
    </div>
      <!-- This inline style should be moved over to our css file when we make one. Just did this for now-->
      <div class="definitions" style="float:right;width:300px;height:900px;overflow:scroll;">
        <!-- For some reason, when i do rake db:seed, the words come out in reverse order sometimes. So I have had to switch between reverse_each and each below-->
          <% @story.words.reverse_each do |wordobj| %>
            <div class="<%= wordobj.id %> def" style="position:fixed;width:300px;">

              <p><h3 class="subheader"><b><%= simple_format(wordobj.name) %></b></h3></p>

              <p><h4><em><%= simple_format(wordobj.definition.downcase) %></em></h4></p>

              <p><blockquote><%= simple_format(wordobj.sentence) %></blockquote></p>
              <!--Still working on this feature.  -->

                <%= button_to "Review Later", "/users/save_word/#{wordobj.id}", :remote => true, :class=>"tiny round button" %>

                <button  class="tiny round button"> No Need </button>
              </div>
              <!--This button takes to us to a save route in the user controller, redirects back to this page, which means as it stands now, everything gets resetted. -->


          <% end %>
      </div>

app/views/stories/show.html.erb.BACKUP.8590.erb
<p id="notice"><%= notice %></p>
    <div style="width:900px;">
      <div class="storyblock" style="float:left;width:500px">
        <p>
          <strong>Name:</strong>
          <%= @story.name %>
          <%= simple_format(@story.content) %>
        </p>
      <% if !@current_user.nil? && @current_user.is_admin==true%>
        <%= link_to 'Edit', edit_story_path(@story) %> |
        <%= link_to 'Back', stories_path %>
    <br/>
    <br/>
    <p><%= link_to "Add Associated Words",  new_word_path(:story_id=>@story.id) %></p>
    <% end %>
    </div>
      <!-- This inline style should be moved over to our css file when we make one. Just did this for now-->
      <div class="definitions" style="float:right;width:300px;height:900px;overflow:scroll;">
        <!-- For some reason, when i do rake db:seed, the words come out in reverse order sometimes. So I have had to switch between reverse_each and each below-->
          <% @story.words.each do |wordobj| %>
<<<<<<< HEAD
            <div class="<%= wordobj.id %> def">
              <label class="Radius Secondary Label"><b><%= simple_format(wordobj.name) %></b></label>
              <label class="Round alert label"><%= simple_format(wordobj.sentence) %></label>
=======
            <div class="<%= wordobj.id %> def" style="position:fixed;width:300px;">
              <p><b><%= simple_format(wordobj.name.capitalize) %></b></p>
              <p><%= simple_format(wordobj.sentence) %></p>
>>>>>>> master
              <p><%= simple_format(wordobj.definition) %></p>
              <!--Still working on this feature.  -->
                <%= button_to "Review Later", "/users/save_word/#{wordobj.id}", :remote => true, :class=>"tiny button" %>
                <button  class="dismiss"> No Need </button>
              </div>
              <!--This button takes to us to a save route in the user controller, redirects back to this page, which means as it stands now, everything gets resetted. -->

          <% end %>
      </div>
  </div>

app/views/stories/show.html.erb.BASE.8590.erb
<p id="notice"><%= notice %></p>
    <div style="width:900px;">
      <div class="storyblock" style="float:left;width:500px">
        <p>
          <strong>Name:</strong>
          <%= @story.name %>
          <%= simple_format(@story.content) %>
        </p>
        <%= link_to 'Edit', edit_story_path(@story) %> |
        <%= link_to 'Back', stories_path %>
      </div>
      <!-- This inline style should be moved over to our css file when we make one. Just did this for now-->
      <div class="definitions" style="float:right;width:300px;height:700px;overflow:scroll;">
        <!-- For some reason, when i do rake db:seed, the words come out in reverse order sometimes. So I have had to switch between reverse_each and each below-->
          <% @story.words.each do |wordobj| %>
            <div class="<%= wordobj.id %> def">
              <p><b><%= simple_format(wordobj.name) %></b></p>
              <p><%= simple_format(wordobj.sentence) %></p>
              <p><%= simple_format(wordobj.definition) %></p>
              <!--Still working on this feature.  -->
              <%= button_to "Review Later", "/users/save_word/#{wordobj.id}", :remote => true %>
              <button class="dismiss"> No Need </button>
              </div>
              <!--This button takes to us to a save route in the user controller, redirects back to this page, which means as it stands now, everything gets resetted. -->

          <% end %>
      </div>
  </div>

app/views/stories/show.html.erb.LOCAL.8590.erb
<p id="notice"><%= notice %></p>
    <div style="width:900px;">
      <div class="storyblock" style="float:left;width:500px">
        <p>
          <strong>Name:</strong>
          <%= @story.name %>
          <%= simple_format(@story.content) %>
        </p>
      <% if !@current_user.nil? && @current_user.is_admin==true%>
        <%= link_to 'Edit', edit_story_path(@story) %> |
        <%= link_to 'Back', stories_path %>
    <br/>
    <br/>
    <p><%= link_to "Add Associated Words",  new_word_path(:story_id=>@story.id) %></p>
    <% end %>
    </div>
      <!-- This inline style should be moved over to our css file when we make one. Just did this for now-->
      <div class="definitions" style="float:right;width:300px;height:700px;overflow:scroll;">
        <!-- For some reason, when i do rake db:seed, the words come out in reverse order sometimes. So I have had to switch between reverse_each and each below-->
          <% @story.words.each do |wordobj| %>
            <div class="<%= wordobj.id %> def">
              <label class="Radius Secondary Label"><b><%= simple_format(wordobj.name) %></b></label>
              <label class="Round alert label"><%= simple_format(wordobj.sentence) %></label>
              <p><%= simple_format(wordobj.definition) %></p>
              <!--Still working on this feature.  -->
                <%= button_to "Review Later", "/users/save_word/#{wordobj.id}", :remote => true, :class=>"tiny button" %>
                <button  class="dismiss"> No Need </button>
              </div>
              <!--This button takes to us to a save route in the user controller, redirects back to this page, which means as it stands now, everything gets resetted. -->

          <% end %>
      </div>
  </div>

app/views/stories/show.html.erb.REMOTE.8590.erb
<p id="notice"><%= notice %></p>
    <div style="width:900px;">
      <div class="storyblock" style="float:left;width:500px">
        <p>
          <strong>Name:</strong>
          <%= @story.name %>
          <%= simple_format(@story.content) %>
        </p>
        <%= link_to 'Edit', edit_story_path(@story) %> |
        <%= link_to 'Back', stories_path %>
      </div>
      <!-- This inline style should be moved over to our css file when we make one. Just did this for now-->
      <div class="definitions" style="float:right;width:300px;height:900px;overflow:scroll;">
        <!-- For some reason, when i do rake db:seed, the words come out in reverse order sometimes. So I have had to switch between reverse_each and each below-->
          <% @story.words.each do |wordobj| %>
            <div class="<%= wordobj.id %> def" style="position:fixed;width:300px;">
              <p><b><%= simple_format(wordobj.name.capitalize) %></b></p>
              <p><%= simple_format(wordobj.sentence) %></p>
              <p><%= simple_format(wordobj.definition) %></p>
              <!--Still working on this feature.  -->
              <%= button_to "Review Later", "/users/save_word/#{wordobj.id}", :remote => true %>
              <button class="dismiss"> No Need </button>
              </div>
              <!--This button takes to us to a save route in the user controller, redirects back to this page, which means as it stands now, everything gets resetted. -->

          <% end %>
      </div>
  </div>