config/routes.rb
Learnbystory::Application.routes.draw do
  post "/users/save_word/:id" => "users#save_word"
  post "/users/review_word/:id" => "users#review_word"
  match "/read" => 'stories#show', :as =>"read"
  resources :words

  resources :stories

  resources :sessions, :except => [:edit, :update, :index]

  resources :users do
    collection do
      get "admin"
      post "admin_create"
    end
  end

  root :to => 'stories#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :story
  attr_accessible :definition, :name, :sentence, :story_id, :is_complete
  has_and_belongs_to_many :users
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  # def add
  #   @word = Word.new(:story_id=>params[:story_id])

  #   respond_to do |format|
  #         format.html # new.html.erb
  #         format.json { render json: @word }
  #   end

  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.js #update.js.erb
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_complete.html.erb
<%= form_for word, :remote => true do |f| %>
  <%= f.check_box :is_complete %>
  <%= f.submit "Got it" %>

<% end %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :definition %><br />
    <%= f.text_field :definition %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_area :sentence %>
 <!--  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_field :story %>
  </div>
  <div class="field">
    <%= f.label :story_id %><br />
    <%= f.text_field :story_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Words</h1>
<%= link_to 'New Word', new_word_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Definition</th>
    <th>Sentence</th>
    <th>Story</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.name %></td>
    <td><%= word.definition %></td>
    <td><%= word.sentence %></td>
    <td><%= word.story_id %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @word.name %>
</p>

<p>
  <b>Definition:</b>
  <%= @word.definition %>
</p>

<p>
  <b>Sentence:</b>
  <%= @word.sentence %>
</p>

<p>
  <b>Story:</b>
  <%= @word.story %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>

app/views/words/update.js.erb
  <% if @word.is_complete? %>
    $("#complete_words").append($("#edit_word_<%= @word.id %>"));
  <% else %>
    $("#incomplete_words").append($("#edit_word_<%= @word.id %>"));
  <% end %>