config/routes.rb
Learnbystory::Application.routes.draw do
  post "/users/save_word/:id" => "users#save_word"
  post "/users/review_word/:id" => "users#review_word"
  match "/read" => 'stories#show', :as =>"read"
  resources :words

  resources :stories

  resources :sessions, :except => [:edit, :update, :index]

  resources :users do
    collection do
      get "admin"
      post "admin_create"
    end
  end

  root :to => 'stories#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>


    <% unless  !@current_user.nil? && @current_user.is_admin==true %>
    <nav class="top-bar">






      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "LearnbyStory", stories_path %></a></h1>
        </li>
      </ul>

       <ul class="right">
         <li class="divider"></li>
         <li class="name">
           <h5><% if @current_user %>
         Hello, <%= @current_user.name %>
          <%= link_to "Log out", session_path("anything"), :method => "delete" %>
          <% else %></h5>
          <h5><%= link_to "Signup", new_user_path %>
          <%= link_to "Log in", new_session_path %>
          <% end %></h5>
         </li>
      </ul>



      <% unless  @current_user.nil?%>

      <section class="top-bar-section">
        <ul class="left">
          <li class="divider"></li>
          <li><%= link_to "View Stories", stories_path %></li>
          <li class="divider"></li>
         <li><%= link_to "Review list", "/users/review_word/#{@current_user.id}", :method => "post" %></li>
          <li class="divider"></li>
          <li><%= link_to "Account","/users/#{@current_user.id}" %></li>
            <% end %>

        </ul>
      </section>



    </nav>
    <% end %>

    <% if !@current_user.nil? && @current_user.is_admin==true%>

    <nav class="top-bar">






      <ul class="title-area">
        <li class="name">
          <h3><%= link_to "Admin View", stories_path %></a></h>
        </li>
      </ul>

       <ul class="right">
         <li class="divider"></li>
         <li class="name">
           <h5><% if @current_user %>
         Hello, <%= @current_user.name %>
          <%= link_to "Log out", session_path("anything"), :method => "delete" %>
          <% else %></h5>
          <h5><%= link_to "Signup", new_user_path %>
          <%= link_to "Log in", new_session_path %>
          <% end %></h5>
         </li>
      </ul>




      <section class="top-bar-section">
        <ul class="left">
          <li class="divider"></li>
          <li><%= link_to "USER TABLE", users_path %></li>
          <li class="divider"></li>

          <li><%= link_to "STORY TABLE", stories_path %></li>
          <li class="divider"></li>

          <li><%= link_to "WORD TABLE", words_path %></li>
          <li class="divider"></li>
        </ul>
      </section>



    </nav>
    <%end%>



  <!-- JJJJ creates flash alerts and notices to be used later via controllers
  ie the controller will let the view know which views need which notice or alert
   -->
   <div class="row"></div>
    <div class="large-5 columns"></div>

  <div class="row">
    <div class="large-7 columns">

      <h4 class="subheader"><% unless flash[:notice].blank? %>
       <p id="flash_notice"><%= flash[:notice] %></p></h4>
      <% end %>

      <h4 class="subheader"><% unless flash[:alert].blank? %>
       <p id="flash_alert"><%= flash[:alert] %></p></h4>

     <% end %>
    </div>
<br/>

<br/>
<br/>


    <%= yield %>


    <%= javascript_include_tag "application" %>
  </body>
</html>